# Generated by Django 5.1.1 on 2024-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='github_link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_link_backend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_link_frontend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
