# Generated by Django 5.1.1 on 2024-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_features_remove_portfolio_live_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
