# Generated by Django 5.1.1 on 2024-10-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_image_portfolio_image_1_portfolio_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
